 
<?php 

/**application/layouts/scripts/layout.phtml
 * 
 */ 
echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>Room Booking</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head> 
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Room Booking</b>
    </div>
    <div id="header-logo" style="float: right">
        <b><a href="<?php echo $this->url(
    array(
        'controller' => 'logout'
        
    ), 
    'default', 
    true) ?>">Logout</a></b>
    </div>
    
</div>

<?php echo $this->layout()->content ?>

</body>
</html>
